services:
  acme_api.event.authentication_failure_listener:
    class: App\Domain\EventListener\AuthenticationFailureListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }
  acme_api.event.authentication_success_listener:
    class: App\Domain\EventListener\AuthenticationSuccessListener
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
  acme_api.event.jwt_invalid_listener:
    class: App\Domain\EventListener\JWTListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }
  acme_api.event.jwt_expired_listener:
    class: App\Domain\EventListener\JWTListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onJWTExpired }